on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    env:
      XDG_RUNTIME_DIR: /tmp/run
      XDG_CONFIG_HOME: /tmp/config
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install pulseaudio-utils taskwarrior
      - run: |
          mkdir -pv ${XDG_RUNTIME_DIR}
          chmod -Rc 700 ${XDG_RUNTIME_DIR}
      - run: "yes | task || true"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - run: cargo test --verbose
        env:
          TODO_FILE: "/dev/null"

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
